nf_core_version: 3.3.1
repository_type: pipeline
template:
  author: Christopher Hakkaart
  description: An nf-core demo pipeline
  force: false
  is_nfcore: true
  name: demo
  org: nf-core
  outdir: .
  version: 1.0.2
